### ISSUE TITLE
Uncaught TypeError: Cannot read property 'redoStack' of undefined

### ISSUE THREAD

**Issue by rcrooks** [paradoxxxzero/atom-undo-tree#2]
Wasn't doing anything special just typing....

**Atom**: 1.21.0-beta1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [undo-tree](https://github.com/paradoxxxzero/atom-undo-tree) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'redoStack' of undefined

```
At /Users/rcrooks/.atom/packages/undo-tree/lib/undo-tree.js:23

TypeError: Cannot read property 'redoStack' of undefined
    at TextEditor.transact (/packages/undo-tree/lib/undo-tree.js:23:16)
    at TextEditor.module.exports.TextEditor.moveCursors (/private/var/folders/4f/7s1xcy6d4t7fjnpxy_dkxmnrjrz47n/T/AppTranslocation/03E95AFA-758C-41E1-9A25-42D9B05046C4/d/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2174:25)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/private/var/folders/4f/7s1xcy6d4t7fjnpxy_dkxmnrjrz47n/T/AppTranslocation/03E95AFA-758C-41E1-9A25-42D9B05046C4/d/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1969:25)
    at TextEditorComponent.didMouseDownOnContent (/private/var/folders/4f/7s1xcy6d4t7fjnpxy_dkxmnrjrz47n/T/AppTranslocation/03E95AFA-758C-41E1-9A25-42D9B05046C4/d/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:1785:25)
```

### Commands

```
```

### Non-Core Packages

```
afterglow-syntax 1.0.0 
afterglow-ui 0.21.1 
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-php 1.2.0 
atom-beautify 0.30.5 
atom-ide-ui 0.3.3 
atom-json-color 0.6.0 
atom-package-sync 0.2.6 
autoclose-html 0.23.0 
autocomplete-json 5.5.0 
autoupdate-packages 1.3.1 
behave-theme 1.7.0 
busy-signal 1.4.3 
clear-night-syntax 1.3.12 
clear-night-ui 1.3.7 
colorful-json 1.1.0 
dash 1.7.1 
Delete-Whitelines 0.6.3 
docblockr 0.11.0 
double-tag 0.9.0 
easy-blue-yellow-syntax 1.0.0 
eclectic-syntax 0.3.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.12 
full-yellow-syntax 0.1.0 
gaia-dark-syntax 2.1.0 
gruvbox-plus-syntax 1.3.1 
html-outliner 0.1.1 
ide-json 0.1.0 
ide-php 0.6.8 
indent-guide-improved 1.4.13 
intentions 1.1.5 
isotope-ui 2.8.5 
javascript-snippets 1.2.1 
linter 2.2.0 
linter-jshint 3.1.5 
linter-ui-default 1.6.10 
Lucario 2.2.0 
multi-cursor 2.1.5 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
northem-dark-atom-syntax 2.1.0 
northem-dark-atom-ui 2.1.0 
nova-atom-syntax 1.5.0 
nucleus-dark-ui 0.12.3 
oceanic-reef-syntax 0.9.0 
onyx-obsidian-syntax 0.6.0 
patagonia-syntax 0.1.2 
php-fmt 0.1.2 
pigments 0.40.2 
playa-dark-syntax 2.1.0 
predawn-syntax 1.0.4 
prettier-atom-with-tabs 0.18.4 
pristine-ui 1.1.10 
pubster-syntax 3.0.2 
pure-syntax 0.3.0 
quilt-syntax 0.4.0 
red-wavy-underline 0.3.3 
rosa-syntax 0.2.1 
rusty-dark-syntax 0.7.0 
seabed-syntax 0.2.0 
selection-to-file 0.6.0 
seti-ui 1.9.0 
seti-ui-red 0.13.0 
sidebar-sync 0.5.0 
simple-drag-drop-text 0.3.4 
slickedit-select 1.6.2 
slime 2.1.0 
smart-tags 0.1.5 
sort-lines 0.15.0 
Sublime-Style-Column-Selection 1.7.4 
summertime-syntax 0.1.0 
tag 0.5.0 
toggler 0.3.0 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.4.0 
tuesday-syntax 0.1.2 
undo-tree 0.2.0 
volt-atom-syntax 0.3.2 
w3c-validation 0.4.0 
zooce-syntax 1.0.1 
```

**Comment by paradoxxxzero** [comment]
It should work with the 1.0.0 version. Thanks for the report

**Comment by rcrooks** [comment]
hmmmm.....seeing this again both in 1.27 and 1.28b0
[Enter steps to reproduce:]

1. Happens when I click anywhere in a document
2. Renders Atom unusuable :(

**Atom**: 1.28.0-beta0 x64
**Electron**: 2.0.0
**OS**: Mac OS X 10.13.5
**Thrown From**: [undo-tree](https://github.com/paradoxxxzero/atom-undo-tree) package 0.2.0


### Stack Trace

Uncaught TypeError: Cannot read property 'redoStack' of undefined

```
At /Users/rcrooks/.atom/packages/undo-tree/lib/undo-tree.js:23

TypeError: Cannot read property 'redoStack' of undefined
    at TextEditor.transact (/packages/undo-tree/lib/undo-tree.js:23:17)
    at TextEditor.moveCursors (/private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/14B53BCC-08D5-4B86-B34A-AFE0E7873700/d/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2875:23)
    at TextEditor.setCursorScreenPosition (/private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/14B53BCC-08D5-4B86-B34A-AFE0E7873700/d/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2686:23)
    at TextEditorComponent.didMouseDownOnContent (/private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/14B53BCC-08D5-4B86-B34A-AFE0E7873700/d/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:1808:25)
```

### Commands

```
```

### Non-Core Packages

```
afterglow-syntax 0.6.0 
afterglow-ui 0.9.0 
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-php 1.2.0 
api-workbench 0.8.48 
apidoc-snippets 0.1.1 
atom-beautify 0.32.3 
atom-html-preview 0.2.5 
atom-ide-ui 0.11.2 
atom-json 0.6.0 
atom-json-color 0.6.0 
atom-minify 0.8.0 
atom-package-sync 0.2.6 
atom-relaxed-syntax 1.0.2 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autocomplete-json 5.5.2 
autocomplete-paths 1.0.5 
autoupdate-packages 1.3.1 
ayu-mirage-atom-syntax 1.0.0 
birds-syntax 0.2.1 
blacksmith-syntax 0.12.0 
blau-dark-syntax 2.2.1 
block-select 1.0.0 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
clearnight-retro-syntax 1.0.1 
clearnight-retro-ui 1.0.1 
colorful-json 1.1.0 
cool-beans-syntax 0.2.8 
cool-beans-ui 0.1.9 
Delete-Whitelines 0.6.3 
desatur-syntax 1.2.3 
directory-color 0.3.0 
docblockr 0.13.7 
double-tag 1.5.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
fairyfloss 0.2.0 
fancy-bracket-matcher 2.1.0 
fascination-syntax 15.5.34 
file-icons 2.1.20 
gaia-dark-syntax 2.1.0 
gist-it 0.9.2 
highlight-line 0.12.0 
highlight-selected 0.13.1 
html-tag-auto-complete 0.1.1 
html-wrapper 0.2.0 
iceberg-syntax 0.2.3 
ide-css 0.3.0 
ide-html 0.4.2 
ide-json 0.2.1 
ide-php 0.7.14 
ide-yaml 0.4.3 
indent-guide-improved 1.4.13 
intentions 1.1.5 
javascript-snippets 1.2.1 
json-refs 0.1.3 
line-number-color 0.2.0 
linter 2.2.0 
linter-htmllint 1.0.1 
linter-js-yaml 1.3.0 
linter-jshint 3.1.8 
linter-json-lint 0.1.3 
linter-languagetool 0.7.1 
linter-raml 1.0.1 
linter-swagger 0.4.2 
linter-ui-default 1.7.1 
lunarized-syntax 0.4.0 
magus-dark-syntax 2.0.0 
markdown-table-editor 1.1.0 
minima-syntax 0.0.2 
minima-ui 0.0.4 
miniprettier 0.5.1 
moonlight 0.7.0 
multi-cursor 2.1.5 
NatureBoi 2.0.0 
naturegreen-dark-syntax 0.1.1 
nefelio-dark-syntax 2.0.0 
noir-dark-syntax 0.1.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
northem-dark-atom-syntax 2.1.0 
northem-dark-atom-ui 2.1.0 
nova-atom-syntax 1.4.1 
nova-atom-ui 1.3.0 
obscurity-syntax 0.6.0 
oliveira-dark-syntax 3.0.0 
one-liner 0.1.3 
pear-dark-syntax 1.0.6 
peterbumsflocke-dark-ui 6.0.0 
peterbumsflocke-syntax 5.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
playa-dark-syntax 2.1.0 
predawn-syntax 1.0.4 
prettier-atom-with-tabs 0.18.4 
pristine-ui 1.1.11 
quietude-syntax 1.3.3 
quilt-syntax 0.4.0 
rain-syntax 2.1.2 
rain-ui 1.0.1 
raml 0.2.0 
raml-snippets 0.1.0 
red-wavy-underline 0.3.3 
resonance-syntax 0.2.0 
resonance-ui 0.11.0 
rusty-dark-syntax 0.7.0 
sector-one-syntax 0.1.0 
select-text-between-tags 0.1.0 
seti-ui 1.10.0 
simple-drag-drop-text 0.4.0 
slickedit-select 1.6.2 
smart-save 0.6.1 
smart-tags 0.1.5 
snake-paste 0.1.0 
splash-ui 0.4.0 
Sublime-Style-Column-Selection 1.7.4 
swap-copy-paste 0.3.0 
sync-settings 0.8.6 
tag 0.5.0 
talamasca 1.3.0 
teletype 0.13.2 
tempo-theme 0.3.0 
toggle-snake-camel 0.3.0 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.5.0 
tuesday-syntax 0.1.2 
undo-tree 0.2.0 
w3c-validation 0.4.0 
white-cursor 0.7.0 
wingyplus-syntax 0.5.1 
wingyplus-ui 0.1.1 
```

**Comment by paradoxxxzero** [comment]
Thanks I'll look into it when I'm back from vacation

Le mar. 15 mai 2018 à 20:28, Robert Crooks <notifications@github.com> a
écrit :

**Comment by rcrooks** [comment]
@paradoxxxzero I think it's ok. I somehow seem to have gotten reverted to an earlier version of the package - once I updated, all seems well. Sorry for the alarm.
